services:
  wgdashboard:
    image: ghcr.io/wgdashboard/wgdashboard:v4.3.3
    restart: unless-stopped
    container_name: wgdashboard
    network_mode: host # Para que el contenedor y el host compartan la red. En el puerto 10086 esta el panel web y el puerto 51820 es el de la VPN
    environment:
      - tz=${TZ:-Europe/Madrid}
      - global_dns=${GLOBAL_DNS}
      - public_ip=${DDNS} # Cuando genera un cliente (peer) en el fichero .conf usara el DDNS
      - username=${USER}
      - password=${PASSWORD}
    volumes:
      - ${DOCKER_DIR}/wg/aconf:/etc/amnezia/amneziawg
      - ${DOCKER_DIR}/wg/wireguard:/etc/wireguard
      - ${DOCKER_DIR}/wg/data:/data
    cap_add:
      - NET_ADMIN # Permite al contenedor crear interfaces WireGuard y tocar reglas de red en la maquina anfitrion
      - SYS_MODULE # Permitir al contenedor cargar módulos del kernel
