services:
  teslamate:
    image: teslamate/teslamate:4.0.1
    container_name: teslamate
    restart: always
    environment:
      - ENCRYPTION_KEY=${ENCRYPTION_KEY}
      - DATABASE_USER=${DATABASE_USER}
      - DATABASE_PASS=${DATABASE_PASS}
      - DATABASE_NAME=${DATABASE_NAME}
      - DATABASE_HOST=${DATABASE_HOST}
      - MQTT_HOST=${MQTT_HOST}
      # Tesla Fleet API
      - TESLA_API_HOST=https://fleet-api.prd.eu.vn.cloud.tesla.com
      - TESLA_AUTH_HOST=https://auth.tesla.com
      - TESLA_AUTH_PATH=/oauth2/v3
      - TESLA_AUTH_CLIENT_ID=${TESLA_AUTH_CLIENT_ID}
    ports:
      - 4000:4000
    volumes:
      - ${DOCKER_DIR}/teslamate/import:/opt/app/import
    cap_drop:
      - all

  database-teslamate:
    image: postgres:18-trixie
    container_name: teslamate-db
    restart: always
    environment:
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASS}
      - POSTGRES_DB=${DATABASE_NAME}
    volumes:
      - ${DOCKER_DIR}/teslamate/teslamate-db:/var/lib/postgresql

  grafana-teslamate:
    image: teslamate/grafana:latest
    container_name: teslamate-grafana
    restart: always
    environment:
      - DATABASE_USER=${DATABASE_USER}
      - DATABASE_PASS=${DATABASE_PASS}
      - DATABASE_NAME=${DATABASE_NAME}
      - DATABASE_HOST=${DATABASE_HOST}
    ports:
      - 3000:3000
    volumes:
      - ${DOCKER_DIR}/teslamate/teslamate-grafana-data:/var/lib/grafana