services:
  mosquitto:
    image: eclipse-mosquitto:2.1.2-alpine
    container_name: mosquitto
    restart: unless-stopped
    ports:
        - "1883:1883"
    volumes:
        - ${DOCKER_DIR}/mosquitto/config:/mosquitto/config
        - ${DOCKER_DIR}/mosquitto/data:/mosquitto/data
        - ${DOCKER_DIR}/mosquitto/log:/mosquitto/log
