services:
    zigbee2mqtt:
        container_name: zigbee2mqtt
        image: ghcr.io/koenkk/zigbee2mqtt:2.10
        restart: unless-stopped
        volumes:
            - ${DOCKER_DIR}/zigbee2mqtt/data:/app/data
        ports:
            # Frontend port
            - 8080:8080
        environment:
            - TZ=${TZ:-Europe/Madrid}
# La sección 'devices' se ha eliminado porque uso una antena a la que nos conectaremos por red
